spring:
  shardingsphere:
    datasource:
      names: master0,slave0
      master0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3307/geektest
        username: root
        password: 123456
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3308/geektest
        username: root
        password: 123456
      sharding:
        master-slave-rules:
          ms0:
            master-data-source-name: master0
            slave-data-source-names: slave0
        tables:
          table1:
            actual-data-nodes: ms0.table1
            table-strategy:
              inline:
                sharding-column: id
                algorithm-expression: table1
            key-generator:
              column: id
              type: SNOWFLAKE
    props:
      sql:
        show: true
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath*:mapper/*